# Generated by Django 5.1 on 2026-06-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_id'], name='account_use_user_id_c25fcb_idx'),
        ),
    ]
