# Generated by Django 5.1 on 2026-06-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0002_user_account_use_user_id_c25fcb_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['admin_id'], name='administrat_admin_i_f786bb_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_id'], name='shopping_ca_categor_061553_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_id'], name='shopping_it_item_id_8b7543_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_id'], name='shopping_pu_purchas_4abb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedetail',
            index=models.Index(fields=['purchase_detail_id'], name='shopping_pu_purchas_84a25d_idx'),
        ),
    ]
