# Generated by Django 5.1 on 2026-06-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0003_admin_administrat_admin_i_f786bb_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='purchase_id',
            new_name='purchase',
        ),
    ]
