# Generated by Django 5.1 on 2026-06-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0004_rename_category_id_cart_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='manufacture',
            new_name='manufacturer',
        ),
    ]
