# Generated by Django 5.1 on 2026-06-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0005_rename_manufacture_item_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='category',
            new_name='user',
        ),
    ]
