# Generated by Django 5.1 on 2026-06-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsite', '0006_rename_category_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='ammount',
            new_name='amount',
        ),
    ]
